name: PHPUnit
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  testing:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: [8, 7.4, 7.3, 7.2, 7.1]
        phpunit-versions: [latest]

    steps:
      - uses: actions/checkout@v2
      - name: Install PHP versions
        uses: shivammathur/setup-php@v2
        with:
          extensions: mbstring, dom, fileinfo,pdo_sqlite,sqlite
          coverage: xdebug
          php-version: ${{ matrix.php-versions }}

      - name: Get Composer Cache Directory 2
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        id: actions-cache
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.php-versions }}-${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ matrix.php-versions }}-${{ runner.os }}-composer-

      - name: Cache PHP dependencies
        uses: actions/cache@v2
        id: vendor-cache
        with:
          path: vendor
          key: ${{ matrix.php-versions }}-${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}

      - name: Install Dependencies
        run: composer install --prefer-dist --optimize-autoloader

      - name: Run PHPUnit Test
        run: XDEBUG_MODE=coverage ./vendor/bin/phpunit --testdox --coverage-clover ./coverage.xml

      - name: Upload to Codecov
        if: ${{ matrix.php-versions }} == 8
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODE_COV_TOKEN }}
          files: ./coverage.xml
          verbose: true
